#!/usr/bin/env python3
"""Compare primary gguf-py observations with isolated secondary output."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def numeric(value: Any) -> int | float | None:
    if value is None:
        return None
    if isinstance(value, dict) and "value" in value:
        value = value["value"]
    return float(value) if isinstance(value, str) and "." in value else int(value)


def primary_inventory(document: dict[str, Any]) -> dict[str, dict[str, int]]:
    return {
        row["encoding"]: {
            "tensorCount": row["tensorCount"],
            "elementCount": row["elementCount"],
            "byteLength": row["byteLength"],
        }
        for row in document["summary"]["encodingInventory"]
    }


def secondary_inventory(document: dict[str, Any]) -> dict[str, dict[str, int]]:
    rows = document["format_extensions"]["gguf"]["on_device_llm"]["storage"]["encoding_inventory"]
    return {
        row["dtype"]: {
            "tensorCount": row["tensor_count"],
            "elementCount": int(row["element_count"]),
            "byteLength": int(row["byte_length"]),
        }
        for row in rows
    }


def compare_inventory(primary: dict[str, Any], secondary: dict[str, Any]) -> dict[str, Any]:
    storage = secondary["format_extensions"]["gguf"]["on_device_llm"]["storage"]
    checks = {
        "artifactSha256": primary["source"]["sha256"] == secondary["identity"]["sha256"],
        "artifactByteLength": primary["source"]["bytes"] == secondary["identity"]["byte_length"],
        "tensorCount": primary["summary"]["tensorCount"] == secondary["format_extensions"]["gguf"]["tensor_count"],
        "elementCount": primary["summary"]["elementCount"] == int(storage["serialized_parameter_count"]),
        "serializedTensorBytes": primary["summary"]["serializedTensorBytes"] == int(storage["serialized_tensor_bytes"]),
        "encodingInventory": primary_inventory(primary) == secondary_inventory(secondary),
        "serializedDescriptorProjectionSha256": (
            primary["summary"]["serializedDescriptorProjectionSha256"]
            == storage["tensor_encoding_assignment_sha256"]
        ),
    }
    return {
        "subject": primary["source"]["id"],
        "checks": checks,
        "allChecksPass": all(checks.values()),
        "primarySerializedDescriptorProjectionSha256": primary["summary"]["serializedDescriptorProjectionSha256"],
        "secondarySerializedDescriptorProjectionSha256": storage["tensor_encoding_assignment_sha256"],
    }


def compare_imatrix(primary: dict[str, Any], secondary: dict[str, Any]) -> dict[str, Any]:
    numerical = secondary["format_extensions"]["gguf"]["tensor_numerical_integrity"]
    scan = primary["numericalScan"]
    checks = {
        "assessedTensorCount": scan["assessedTensorCount"] == int(numerical["assessed_tensor_count"]),
        "decodedValueCount": scan["decodedValueCount"] == numeric(numerical["decoded_value_count"]),
        "nonfiniteValueCount": scan["nonfiniteValueCount"] == numeric(numerical["nonfinite_value_count"]),
        "exactZeroValueCount": scan["exactZeroValueCount"] == numeric(numerical["exact_zero_value_count"]),
        "allZeroTensorCount": scan["allZeroTensorCount"] == numeric(numerical["all_zero_tensor_count"]),
        "constantTensorCount": scan["constantTensorCount"] == numeric(numerical["constant_tensor_count"]),
    }
    return {
        "subject": primary["source"]["id"],
        "checks": checks,
        "allChecksPass": all(checks.values()),
    }


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    experiment = root / "experiments/gguf-imatrix"
    results = experiment / "results"
    raw = experiment / "crosschecks/deepbom/raw"
    comparisons = [
        compare_inventory(load(results / "ibm-q4km-tensor-inventory.json"), load(raw / "ibm-q4km.json")),
        compare_inventory(load(results / "bartowski-q4km-tensor-inventory.json"), load(raw / "bartowski-q4km.json")),
    ]
    imatrix_primary = load(results / "imatrix-measurement.json")
    imatrix_secondary = load(raw / "bartowski-imatrix.json")
    comparisons.append(compare_inventory(imatrix_primary, imatrix_secondary))
    numerical = compare_imatrix(imatrix_primary, imatrix_secondary)
    report = {
        "recordType": "tensor-quantization-metadata-study.gguf-secondary-implementation-comparison.v1",
        "primaryImplementation": "upstream gguf-py 0.19.0",
        "secondaryImplementation": "DeepBOM output generated by an implementation maintained by the study author",
        "epistemicBoundary": (
            "The second path checks reproducibility across implementations. It is not an "
            "independent publisher attestation and no primary claim depends solely on it."
        ),
        "inventoryComparisons": comparisons,
        "importanceMatrixNumericalComparison": numerical,
        "allChecksPass": all(item["allChecksPass"] for item in comparisons) and numerical["allChecksPass"],
    }
    output = experiment / "crosschecks/deepbom/normalized-comparison.json"
    output.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
